#pragma once

#define MSAA_COUNT 4

typedef enum _CLEAR_FLAGS
{
	CF_CLEAR_COLOR	 = 1 << 0,
	CF_CLEAR_STENCIL = 1 << 1,
	CF_CLEAR_ZBUFFER = 1 << 2,
} CLEAR_FLAGS;

typedef enum _RENDER_COLOR_BUFFER_INDEX
{
	RCBI_COLOR_BUFFER = 0,
	RCBI_NORMAL_BUFFER = 1,
	RCBI_DEPTH_BUFFER = 2,

	RCBI_BUFFER_MAX
} RENDER_COLOR_BUFFER_INDEX;
